name: Build and deploy the website

on:
  push:
    branches: [ site ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        yarn global add gatsby-cli
        yarn install
    - name: Build gatsby website
      run: |
        PATH="${HOME}/.yarn/bin:${PATH}"
        gatsby build
        
